"$schema" = 'https://starship.rs/config-schema.json'

format = """
[â•­â”€](bold 250)$directory\
$git_branch\
$git_status\
$fill\
$status\
$python\
$rust\
$nodejs\
$cpp\
$sudo\
$shell\
$line_break\
[â•°â”€](bold 250)$character\
"""
add_newline = false

[directory]
format = '[ ï¼  $path]($style)[ $read_only]($read_only_style) '
style = 'bold 218'
read_only_style = 'red'
home_symbol = "~"
truncation_symbol = '.../'
truncation_length = 4
read_only = 'ó° '
use_os_path_sep = true
truncate_to_repo = true

[git_branch]
format = """
[ó°Š¤ ](bold 250)[ $symbol$branch(:$remote_name/$remote_branch)]($style)\
"""
#  ï—   ï™  ï˜  ï‘¿  ï‡“  î‚   |
symbol = 'ï™ '
style = 'bold 153'
always_show_remote = false
disabled = false

[git_status]
format = '( [\[$all_status$ahead_behind\]]($style) ) '
style = 'bold red'
untracked ='?'
staged ='+'
modified = '!'
deleted = 'x'

[fill]
symbol = ' '
style = 'bright-black'
disabled = false

[status]
# '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
format = '$symbol'
symbol = '[â—\($status\)](bright-red) '
success_symbol = '[â—](green) '
not_executable_symbol = '[âŒ½\($status\)](bright-red) '
not_found_symbol = '[â—\($status\)](bright-red) '
sigint_symbol = '[âœ¶\($status\)](bright-red) '
signal_symbol = '[âœ•\($status\)](bright-red) '
recognize_signal_code = true
map_symbol = true
disabled = false

[cmd_duration] #  ïƒ§  ï„  ï‰’  |
format = '[â˜—](bright-red)[ $duration]($style) '
style = 'bold yellow'
min_time = 2000
show_milliseconds = false
disabled = true

[cpp]
disabled = false
format = '[$name $version]($style) '

[python]
format = '[$symbol${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = 'ó°Œ  '
style = 'bold bright-yellow'
#detect_files = [['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini', 'pixi.toml']]
version_format = '${major}.${minor}'
disabled = false

[rust]
format = '[ó±˜— $version](202 bold) '

[aws]
# 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
format = '[$symbol](bold green)[( $profile)]($style) '
symbol = 'ïƒ‚ '
style = 'bright-purple'
disabled = true

[sudo]
# ïƒ§  ï…• ï‚„  ï‡  î½¤   |
format = '[$symbol]($style)'
symbol = 'ï‚„ '
style = 'bold 9'
allow_windows = true
disabled = false

[shell] #  î¯… ï’‰  îš‘ ï‘ _ |
format = '[ï‘ _ $indicator]($style) '
style = 'bold 183'
unknown_indicator = '???'
powershell_indicator = 'pwsh'
fish_indicator = 'fish'
bash_indicator = 'bash'
zsh_indicator = 'zsh'
disabled = false

[username]
# ï•  ï‹€  î´µ  ï€‡  î´µ  |
format = '[ï•](bold 250)[ $user]($style)'
style_user = 'bold yellow'
style_root = 'bold red'
show_always = true

[hostname]
format = '[([ïƒ‚ ]($style)$hostname)](bold bright-cyan)'
ssh_symbol = 'ğŸŒ ' # î½‹  |
style = 'bold green'
ssh_only = true
trim_at = ''
aliases = { "loganmac.local" = "mac" }
disabled = true

[character]
format = '$symbol '
success_symbol = '[ï”](bold 250)'
error_symbol = '[âœ˜](bold red)'
vimcmd_symbol = '[V](bold 250)'

